version: '2'

services:
    Skoczkowie:
        image: michalmaciszka/be_175718
        ports:
            # - 5718:80
            - 5718:443
        environment:
            - PS_INSTALL_AUTO=1
            - PS_DEV_MODE=1
            - DB_SERVER=actina15.maas
            - DB_USER=be_175718
            - DB_PASSWD=pass
            - DB_NAME=be_175718
            - PS_FOLDER_ADMIN=admin
            - PS_FOLDER_INSTALL=install
            - PS_ERASE_DB=0
            - PS_DOMAIN=localhost:5717
            - PS_DOMAIN_SSL=localhost:5718
        restart: always
