<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3leapy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3leapy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ3leapy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ3leapy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ3leapy\appProdProjectContainer([
    'container.build_hash' => 'Z3leapy',
    'container.build_id' => 'c05aacee',
    'container.build_time' => 1636989962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3leapy');
